### PR TITLE
it seems that this new version is true and old not

### LINKED ISSUE #2: Installation istructions fail - at least for confused people like me
> copy /lib/git-resolve-conflict.sh to your .bashrc (this adds just git resolve-conflict)

I copied file contents into my .bashrc file. Not sure how it would add `git ...` but I tried anyway.

Predictably `git resolve-conflict --theirs app/src/main/res/values-da/strings.xml` failed with

`git: 'resolve-conflict' is not a git command. See 'git --help'.``

(because why adding function to `.bashrc` file would create a git function? 

Maybe `.gitconfig` also should be modified? I have for example `	lg = "!gitk --all&"` there.

Looking at how it is defined I expected `resolve-conflict() --theirs app/src/main/res/values-da/strings.xml` to work, but this failed with

`bash: syntax error near unexpected token `--theirs'`

-------------------------------

Feel free to close it with "hahahahaha, learn to use Linux" but I just wanted to let you know that the current installation instruction is a bit confusing - at least to me.

### PR DESCRIPTION
**Pull request by matkoniecz**
fixes #2

Tested for me, but maybe I screwed something up or should do it differently?

### CODE REVIEW

**Comment by matkoniecz** [comment]
I would be happy to learn why and how I am wrong here.

Is there a chance that fact that my `.bashrc` is a symbolic link to repo with my dotfiles may be breaking something? (for reference: https://github.com/matkoniecz/my_public_dotfiles )

**Comment by jakub-g** [comment]
Hi, thx for the PR!

I agree the instructions are not very clear/thorough.

In fact the command without `-` i.e. `git something` works for me, but I'm based on Windows (using git bash), but it's not trivial how it's supposed to work.

There's some built-in mechanism in git that if you run `git something` it will run `git-something` script. This script must be in `$PATH` *and* be executable:

https://blog.dreamfactory.com/extending-git-with-a-custom-command/

So you'd need to `chmod u+x` the new file if you copy it somewhere.

If you just copy a bash function directly to your `.bashrc`, you'd have to reload your terminal session (and perhaps something more).

**Comment by jakub-g** [comment]
In addition to last statement, on my side I put helpers not into `.bashrc` anymore but into `.profile`. Whenever I change something, I have to `source ~/.profile` to have my shell reloaded with the newly added things.

**Comment by matkoniecz** [comment]
not sure what went wrong here, I admit that I have not time to investigate that

**Pull request closed without merging**
